#!/usr/bin/env bash
# Deploy Hyperlane core contracts to specified chains

# Set SCRIPT_DIR first, before any other logic
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common utilities - use absolute path in container
if [ -f "/usr/local/bin/common.sh" ]; then
    source "/usr/local/bin/common.sh"
else
    echo "ERROR: Could not find common.sh"
    exit 1
fi

# Source template processor
if [ -f "/usr/local/bin/template_processor.sh" ]; then
    source "/usr/local/bin/template_processor.sh"
else
    echo "ERROR: Could not find template_processor.sh"
    exit 1
fi

# ============================================================================
# REGISTRY INITIALIZATION
# ============================================================================

initialize_chain_registry() {
    log_info "Initializing chain registry for all chains"

    # Create registry structure
    ensure_directories "${REGISTRY_DIR}" "${REGISTRY_DIR}/chains"

    # Parse chain configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS

    # Create metadata for all chains upfront
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        local rpc="${RPCS[$chain]:-}"
        local chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")

        local reg_chain_dir="${REGISTRY_DIR}/chains/${chain}"
        ensure_directories "$reg_chain_dir"

        # Create metadata file for this chain
        create_chain_metadata "$chain" "$rpc" "$chain_id" "$reg_chain_dir"

        # CRITICAL: Also copy metadata to where Hyperlane CLI expects it
        # CLI v18+ looks for metadata in $HOME/.hyperlane/chains/<chain-name>/
        local cli_chain_dir="$HOME/.hyperlane/chains/${chain}"
        mkdir -p "$cli_chain_dir"
        cp "${reg_chain_dir}/metadata.yaml" "${cli_chain_dir}/metadata.yaml"

        log_info "Registered chain metadata for ${chain} (ID: ${chain_id}) in both registry and CLI locations"
    done

    # Create a chains.yaml file listing all chains
    create_chains_config_file

    # Also copy chains.yaml to CLI expected location
    mkdir -p "$HOME/.hyperlane"
    cp "${REGISTRY_DIR}/chains.yaml" "$HOME/.hyperlane/chains.yaml"

    # Export registry path for Hyperlane CLI
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"
    # Also export the standard location as fallback
    export HYPERLANE_REGISTRY_DIR="$HOME/.hyperlane"

    log_info "Chain registry initialization complete (available in both registry and CLI standard locations)"
}

create_chains_config_file() {
    local chains_file="${REGISTRY_DIR}/chains.yaml"

    log_info "Creating chains configuration file"

    # Start the YAML file
    echo "# Hyperlane Chains Configuration" > "$chains_file"
    echo "# Auto-generated by deploy_core.sh" >> "$chains_file"
    echo "" >> "$chains_file"

    # Parse configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS

    # Add each chain to the file
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        local rpc="${RPCS[$chain]:-}"
        local chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")

        cat >> "$chains_file" <<EOF
${chain}:
  chainId: ${chain_id}
  domainId: ${chain_id}
  name: ${chain}
  protocol: ethereum
  rpcUrls:
    - http: ${rpc}
  nativeToken:
    name: Ether
    symbol: ETH
    decimals: 18

EOF
    done

    log_info "Chains configuration file created at ${chains_file}"
}

# ============================================================================
# MAIN DEPLOYMENT LOGIC
# ============================================================================

deploy_core_to_chain() {
    local chain_name="$1"
    local rpc_url="$2"
    local chain_id="$3"
    local stamp_file="${CONFIGS_DIR}/.done-core-${chain_name}"

    # Check if already deployed
    if check_stamp_file "$stamp_file"; then
        log_info "Core already deployed for ${chain_name}, skipping"
        return 0
    fi

    # Registry should already be initialized, just get the path
    local reg_chain_dir="${REGISTRY_DIR}/chains/${chain_name}"

    # Check if existing addresses are already registered
    if [ -f "${reg_chain_dir}/addresses.yaml" ]; then
        log_info "Found existing addresses for ${chain_name} in registry, skipping deployment"
        create_stamp_file "$stamp_file"
        display_deployed_addresses "$chain_name"
        return 0
    fi

    # Verify metadata exists
    if [ ! -f "${reg_chain_dir}/metadata.yaml" ]; then
        log_error "Chain metadata not found for ${chain_name}. Registry initialization may have failed."
        exit $ERROR_DEPLOYMENT_FAILED
    fi
    
    # Initialize core configuration
    local core_cfg="${CONFIGS_DIR}/core-${chain_name}.yaml"
    if ! initialize_core_config "$core_cfg"; then
        log_error "Failed to initialize core config for ${chain_name}"
        exit $ERROR_DEPLOYMENT_FAILED
    fi
    
    # Deploy core contracts with retry logic
    if deploy_core_with_retry "$chain_name" "$core_cfg"; then
        # Copy deployment artifacts
        copy_deployment_artifacts "$chain_name" "$reg_chain_dir"
        create_stamp_file "$stamp_file"
        log_info "Successfully deployed core contracts to ${chain_name}"
        # Display the deployed contract addresses
        display_deployed_addresses "$chain_name"
    else
        log_error "Failed to deploy core contracts to ${chain_name}"
        exit $ERROR_DEPLOYMENT_FAILED
    fi
}

create_chain_metadata() {
    local chain_name="$1"
    local rpc_url="$2"
    local chain_id="$3"
    local output_dir="$4"
    
    cat > "${output_dir}/metadata.yaml" <<EOF
name: ${chain_name}
protocol: ethereum
chainId: ${chain_id}
domainId: ${chain_id}
rpcUrls:
  - http: ${rpc_url}
nativeToken:
  name: Ether
  symbol: ETH
  decimals: 18
EOF
    
    log_debug "Created metadata for ${chain_name}"
}


initialize_core_config() {
    local config_file="$1"

    # Reuse existing init output if present to avoid redundant work
    if [ -f "$config_file" ]; then
        log_debug "Reusing existing ${config_file}"
        return 0
    fi

    log_info "Initializing core config"
    
    # Try to run hyperlane core init with proper flags
    # Use --out to specify output location, --registry to use local registry
    # Export chain config path for CLI to recognize custom chains
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"

    # For CLI v18+, use updated syntax
    # Provide empty input for owner address prompt (will use default from key)
    if echo "" | hyperlane core init --yes --out "$config_file" --registry "${REGISTRY_DIR}" 2>&1 | grep -v "TypeError: fetch failed" > /dev/null; then
        if [ -f "$config_file" ]; then
            log_info "Successfully created core config with hyperlane core init"
            return 0
        fi
    fi
    
    # Fallback: Create a valid core config manually
    log_info "Creating core config with ISM type: ${ISM_TYPE:-trustedRelayer}"
    
    # Get the deployer address from the HYP_KEY
    # Using cast to derive address from private key
    local DEPLOYER_ADDRESS=""
    if [ -n "$HYP_KEY" ]; then
        DEPLOYER_ADDRESS=$(cast wallet address "$HYP_KEY" 2>/dev/null || echo "")
        log_info "Derived deployer address: $DEPLOYER_ADDRESS"
    fi
    
    # Use default address if derivation failed
    if [ -z "$DEPLOYER_ADDRESS" ]; then
        DEPLOYER_ADDRESS="0xe1A74e1FCB254CB1e5eb1245eaAe034A4D7dD538"
        log_info "Using default deployer address: $DEPLOYER_ADDRESS"
    fi
    
    # Set template directory based on environment
    local template_dir="${TEMPLATE_DIR:-/templates}"
    if [ ! -d "$template_dir" ]; then
        # Try relative path for local development
        template_dir="${SCRIPT_DIR}/../../templates"
    fi
    
    # Generate ISM configuration from template
    local ism_type="${ISM_TYPE:-trustedRelayer}"
    local ism_config=$(generate_ism_from_template "$ism_type" "$DEPLOYER_ADDRESS" "${template_dir}/ism")
    
    # Generate core configuration from template
    generate_core_config_from_template "$DEPLOYER_ADDRESS" "$ism_config" "${template_dir}/core-config.json" "$config_file"
    
    if [ -f "$config_file" ]; then
        log_debug "Created core config with ISM type: ${ISM_TYPE:-trustedRelayer}"
        return 0
    else
        log_error "Failed to create core config file"
        return 1
    fi
}

deploy_core_with_retry() {
    local chain_name="$1"
    local config_file="$2"
    local log_file="/tmp/deploy-${chain_name}.log"
    
    log_info "Deploying Hyperlane core to ${chain_name}"
    
    # Ensure registry environment is set for deployment
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"

    # For CLI v18+, use updated syntax
    # Define the deployment command with proper registry
    local deploy_cmd="hyperlane core deploy --chain '${chain_name}' --config '${config_file}' --registry '${REGISTRY_DIR}' --key '${HYP_KEY}' --yes 2>&1 | tee '${log_file}'"
    
    # Try deployment with retry on nonce errors
    local attempt=0
    while [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; do
        attempt=$((attempt + 1))
        
        if [ $attempt -gt 1 ]; then
            log_info "🔄 Deployment attempt $attempt/$MAX_RETRY_ATTEMPTS for ${chain_name}..."
        fi
        
        if eval "$deploy_cmd"; then
            if [ $attempt -gt 1 ]; then
                log_info "✅ Deployment succeeded on attempt $attempt for ${chain_name}"
            fi
            return 0
        fi

        # Check for nonce errors
        if grep -q "nonce has already been used\|nonce too low" "$log_file"; then
            if [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; then
                log_info "⚠️  Nonce error detected on ${chain_name}, this may indicate contracts are already deployed"
                log_info "🔄 Retrying deployment (attempt $attempt/$MAX_RETRY_ATTEMPTS)..."
                sleep $RETRY_DELAY
            fi
        elif grep -qi "timeout" "$log_file"; then
            if [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; then
                log_info "⚠️  Timeout when deploying to ${chain_name}, retrying (attempt $attempt/$MAX_RETRY_ATTEMPTS)..."
                sleep $RETRY_DELAY
            fi
        else
            log_error "Deployment failed with non-recoverable error"
            cat "$log_file"
            return 1
        fi
    done
    
    log_error "Deployment failed after $MAX_RETRY_ATTEMPTS attempts"
    return 1
}

extract_ism_address() {
    local chain_name="$1"
    local target_dir="$2"
    local addresses_file="${target_dir}/addresses.yaml"
    
    # Get mailbox address
    local mailbox_addr=$(grep "^mailbox:" "$addresses_file" | cut -d' ' -f2 | tr -d '"')
    
    if [ -n "$mailbox_addr" ]; then
        # Get chain RPC URL
        local rpc_url=""
        for chain in $CHAINS; do
            if [ "$chain" = "$chain_name" ]; then
                rpc_url="${RPCS[$chain]}"
                break
            fi
        done
        
        if [ -n "$rpc_url" ]; then
            # Query defaultIsm from mailbox contract using cast
            local ism_addr=$(cast call "$mailbox_addr" "defaultIsm()(address)" --rpc-url "$rpc_url" 2>/dev/null || echo "")
            
            if [ -n "$ism_addr" ] && [ "$ism_addr" != "" ]; then
                log_debug "Found ISM address for ${chain_name}: ${ism_addr}"
                
                # Add ISM address to addresses.yaml
                if [ -f "$addresses_file" ]; then
                    echo "defaultIsm: ${ism_addr}" >> "$addresses_file"
                else
                    echo "defaultIsm: ${ism_addr}" > "$addresses_file"
                fi
                log_info "Added ISM address to ${chain_name} registry"
            else
                log_debug "Could not extract ISM address for ${chain_name}"
            fi
        fi
    fi
}

copy_deployment_artifacts() {
    local chain_name="$1"
    local target_dir="$2"
    local addresses_file="$HOME/.hyperlane/chains/${chain_name}/addresses.yaml"
    
    if [ -f "$addresses_file" ]; then
        cp "$addresses_file" "$target_dir/"
        log_debug "Copied deployment artifacts for ${chain_name}"
        
        # Extract and add ISM address from mailbox contract
        extract_ism_address "$chain_name" "$target_dir"
    fi
}

display_deployed_addresses() {
    local chain_name="$1"
    local registry_file="${REGISTRY_DIR}/chains/${chain_name}/addresses.yaml"
    
    if [ -f "$registry_file" ]; then
        log_info "✅ Core contract deployments complete for ${chain_name}:"
        echo ""
        # Display the addresses with proper formatting
        while IFS=': ' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
                echo "    $key: $value"
            fi
        done < "$registry_file"
        echo ""
    else
        log_warn "Could not find deployed addresses for ${chain_name}"
    fi
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
    # Validate required environment variables
    require_env_var "CHAIN_NAMES" "CHAIN_NAMES not set"
    require_env_var "HYP_KEY" "HYP_KEY not set (agents.deployer.key). Required for core deployment."

    # Install CLI if needed
    ensure_hyperlane_cli

    # Create necessary directories
    ensure_directories "$CONFIGS_DIR" "${REGISTRY_DIR}"

    # Initialize chain registry BEFORE any deployments
    initialize_chain_registry
    
    # Parse chain configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS
    
    # Deploy to each chain
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        # Validate chain name
        validate_chain_name "$chain"
        
        # Get RPC URL
        rpc="${RPCS[$chain]:-}"
        if [ -z "$rpc" ]; then
            log_error "No RPC URL provided for chain ${chain}"
            exit $ERROR_MISSING_ENV
        fi
        
        # Get or detect chain ID
        chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")
        
        # Deploy core to this chain
        deploy_core_to_chain "$chain" "$rpc" "$chain_id"
    done
    
    # Deploy IGP contracts if enabled (optional but recommended for production)
    if [ "${DEPLOY_IGP:-true}" = "true" ]; then
        log_info "Deploying InterchainGasPaymaster (IGP) contracts..."

        # Get deployer address for IGP configuration
        local DEPLOYER_ADDRESS=""
        if [ -n "$HYP_KEY" ]; then
            DEPLOYER_ADDRESS=$(cast wallet address "$HYP_KEY" 2>/dev/null || echo "")
        fi

        if [ -z "$DEPLOYER_ADDRESS" ]; then
            log_warn "Could not derive deployer address, skipping IGP deployment"
        else
            for chain in "${CHAINS[@]}"; do
                local igp_stamp="${CONFIGS_DIR}/.done-igp-${chain}"

                # Skip if already deployed
                if check_stamp_file "$igp_stamp"; then
                    log_info "IGP already deployed for ${chain}, skipping"
                    continue
                fi

                log_info "Deploying IGP for ${chain}..."

                # Create minimal IGP hook configuration
                cat > "/tmp/igp-hook-${chain}.yaml" <<EOF
type: interchainGasPaymaster
beneficiary: "${DEPLOYER_ADDRESS}"
owner: "${DEPLOYER_ADDRESS}"
oracleKey: "${DEPLOYER_ADDRESS}"
gasOracleType: storageGasOracle
overhead:
  default: 50000
EOF

                # Try to deploy using hyperlane CLI
                local deploy_log="/tmp/deploy-igp-${chain}.log"
                if hyperlane deploy hook \
                    --chain "${chain}" \
                    --config "/tmp/igp-hook-${chain}.yaml" \
                    --registry "${REGISTRY_DIR}" \
                    --key "${HYP_KEY}" \
                    --yes 2>&1 | tee "$deploy_log"; then

                    # Try to extract IGP address from deployment output
                    # Look for patterns like "InterchainGasPaymaster deployed at: 0x..."
                    local igp_addr=$(grep -oP 'InterchainGasPaymaster.*?0x[a-fA-F0-9]{40}' "$deploy_log" | grep -oP '0x[a-fA-F0-9]{40}' | head -1)

                    # Alternative pattern matching if first fails
                    if [ -z "$igp_addr" ]; then
                        igp_addr=$(grep -oP 'deployed.*?0x[a-fA-F0-9]{40}' "$deploy_log" | grep -oP '0x[a-fA-F0-9]{40}' | head -1)
                    fi

                    if [ -n "$igp_addr" ]; then
                        # Update addresses.yaml with IGP address
                        local addr_file="${REGISTRY_DIR}/chains/${chain}/addresses.yaml"

                        # Check if interchainGasPaymaster already exists in file
                        if grep -q "^interchainGasPaymaster:" "$addr_file" 2>/dev/null; then
                            # Update existing entry
                            sed -i "s/^interchainGasPaymaster:.*/interchainGasPaymaster: ${igp_addr}/" "$addr_file"
                        else
                            # Add new entry
                            echo "interchainGasPaymaster: ${igp_addr}" >> "$addr_file"
                        fi

                        # Also update JSON addresses file if it exists
                        local json_file="${CONFIGS_DIR}/addresses-${chain}.json"
                        if [ -f "$json_file" ]; then
                            # Use yq to update JSON
                            yq -i '.interchainGasPaymaster = "'${igp_addr}'"' -o json "$json_file" 2>/dev/null || true
                        fi

                        log_info "✅ IGP deployed for ${chain} at: ${igp_addr}"
                        create_stamp_file "$igp_stamp"
                    else
                        log_warn "⚠️  IGP deployed but could not extract address for ${chain}"
                        # Still mark as done to avoid re-deployment attempts
                        create_stamp_file "$igp_stamp"
                    fi
                else
                    log_warn "⚠️  IGP deployment failed for ${chain}, continuing with zero address fallback"
                    # Don't create stamp file so it can be retried if needed
                fi

                # Small delay between deployments to avoid nonce issues
                sleep 2
            done
        fi
    else
        log_info "IGP deployment disabled (DEPLOY_IGP=false), using zero address as placeholder"
    fi

    # Mark overall deployment as complete
    create_stamp_file "${CONFIGS_DIR}/.deploy-core"
    log_info "Core deployment completed for all chains"
}

# Run main function
main "$@"
