#!/usr/bin/env bash
# Deploy Hyperlane core contracts to specified chains

# Set SCRIPT_DIR first, before any other logic
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common utilities - use absolute path in container
if [ -f "/usr/local/bin/common.sh" ]; then
    source "/usr/local/bin/common.sh"
else
    echo "ERROR: Could not find common.sh"
    exit 1
fi

# Source template processor
if [ -f "/usr/local/bin/template_processor.sh" ]; then
    source "/usr/local/bin/template_processor.sh"
else
    echo "ERROR: Could not find template_processor.sh"
    exit 1
fi

# ============================================================================
# REGISTRY INITIALIZATION
# ============================================================================

initialize_chain_registry() {
    log_info "Initializing chain registry for all chains"

    # Create registry structure
    ensure_directories "${REGISTRY_DIR}" "${REGISTRY_DIR}/chains"

    # Parse chain configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS

    # Create metadata for all chains upfront
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        local rpc="${RPCS[$chain]:-}"
        local chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")

        local reg_chain_dir="${REGISTRY_DIR}/chains/${chain}"
        ensure_directories "$reg_chain_dir"

        # Create metadata file for this chain
        create_chain_metadata "$chain" "$rpc" "$chain_id" "$reg_chain_dir"

        # CRITICAL: Also copy metadata to where Hyperlane CLI expects it
        # CLI v18+ looks for metadata in $HOME/.hyperlane/chains/<chain-name>/
        local cli_chain_dir="$HOME/.hyperlane/chains/${chain}"
        mkdir -p "$cli_chain_dir"
        cp "${reg_chain_dir}/metadata.yaml" "${cli_chain_dir}/metadata.yaml"

        log_info "Registered chain metadata for ${chain} (ID: ${chain_id}) in both registry and CLI locations"
    done

    # Create a chains.yaml file listing all chains
    create_chains_config_file

    # Also copy chains.yaml to CLI expected location
    mkdir -p "$HOME/.hyperlane"
    cp "${REGISTRY_DIR}/chains.yaml" "$HOME/.hyperlane/chains.yaml"

    # Export registry path for Hyperlane CLI
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"
    # Also export the standard location as fallback
    export HYPERLANE_REGISTRY_DIR="$HOME/.hyperlane"

    log_info "Chain registry initialization complete (available in both registry and CLI standard locations)"
}

create_chains_config_file() {
    local chains_file="${REGISTRY_DIR}/chains.yaml"

    log_info "Creating chains configuration file"

    # Start the YAML file
    echo "# Hyperlane Chains Configuration" > "$chains_file"
    echo "# Auto-generated by deploy_core.sh" >> "$chains_file"
    echo "" >> "$chains_file"

    # Parse configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS

    # Add each chain to the file
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        local rpc="${RPCS[$chain]:-}"
        local chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")

        {
            echo "${chain}:"
            echo "  chainId: ${chain_id}"
            echo "  domainId: ${chain_id}"
            echo "  name: ${chain}"
            echo "  protocol: ethereum"
            echo "  rpcUrls:"
            echo "    - http: ${rpc}"
            echo "  nativeToken:"
            echo "    name: Ether"
            echo "    symbol: ETH"
            echo "    decimals: 18"
            echo
        } >> "$chains_file"
    done

    log_info "Chains configuration file created at ${chains_file}"
}

# ============================================================================
# MAIN DEPLOYMENT LOGIC
# ============================================================================

deploy_core_to_chain() {
    local chain_name="$1"
    local rpc_url="$2"
    local chain_id="$3"
    local stamp_file="${CONFIGS_DIR}/.done-core-${chain_name}"

    # Check if already deployed
    if check_stamp_file "$stamp_file"; then
        log_info "Core already deployed for ${chain_name}, skipping"
        return 0
    fi

    # Registry should already be initialized, just get the path
    local reg_chain_dir="${REGISTRY_DIR}/chains/${chain_name}"

    # If we're forcing a redeploy, clear any cached addresses so the CLI
    # doesn't short-circuit the deployment on subsequent runs.
    if [ "${FORCE_DEPLOY_CORE:-false}" = "true" ]; then
        if [ -f "${reg_chain_dir}/addresses.yaml" ]; then
            log_debug "FORCE_DEPLOY_CORE=true, removing cached addresses for ${chain_name}"
            rm -f "${reg_chain_dir}/addresses.yaml"
        fi
        local cli_chain_dir="$HOME/.hyperlane/chains/${chain_name}"
        if [ -f "${cli_chain_dir}/addresses.yaml" ]; then
            log_debug "FORCE_DEPLOY_CORE=true, removing CLI cached addresses for ${chain_name}"
            rm -f "${cli_chain_dir}/addresses.yaml"
        fi
    fi

    # Check if existing addresses are already registered
    if [ -f "${reg_chain_dir}/addresses.yaml" ]; then
        log_info "Found existing addresses for ${chain_name} in registry, skipping deployment"
        ensure_default_ism_recorded "$chain_name" "$rpc_url" "$reg_chain_dir"
        create_stamp_file "$stamp_file"
        display_deployed_addresses "$chain_name"
        return 0
    fi

    # Verify metadata exists
    if [ ! -f "${reg_chain_dir}/metadata.yaml" ]; then
        log_error "Chain metadata not found for ${chain_name}. Registry initialization may have failed."
        exit $ERROR_DEPLOYMENT_FAILED
    fi
    
    # Initialize core configuration
    local core_cfg="${CONFIGS_DIR}/core-${chain_name}.yaml"
    if ! initialize_core_config "$core_cfg"; then
        log_error "Failed to initialize core config for ${chain_name}"
        exit $ERROR_DEPLOYMENT_FAILED
    fi
    
    # Prepare isolated registry for deployment to avoid CLI write/read conflicts
    local temp_registry="/tmp/hyperlane-registry-${chain_name}"
    rm -rf "$temp_registry"
    mkdir -p "$temp_registry/chains/${chain_name}"
    cp "${reg_chain_dir}/metadata.yaml" "$temp_registry/chains/${chain_name}/metadata.yaml"

    cat > "$temp_registry/chains.yaml" <<EOF
${chain_name}:
  chainId: ${chain_id}
  domainId: ${chain_id}
  name: ${chain_name}
  protocol: ethereum
  rpcUrls:
    - http: ${rpc_url}
  nativeToken:
    name: Ether
    symbol: ETH
    decimals: 18
EOF

    # Deploy core contracts into the temporary registry first
    if deploy_core_with_retry "$chain_name" "$core_cfg" "$temp_registry"; then
        local temp_addresses="$temp_registry/chains/${chain_name}/addresses.yaml"
        if [ -f "$temp_addresses" ]; then
            cp "$temp_addresses" "$reg_chain_dir/addresses.yaml"
        else
            log_warn "Addresses file missing in temporary registry for ${chain_name}"
        fi

        ensure_default_ism_recorded "$chain_name" "$rpc_url" "$reg_chain_dir"
        create_stamp_file "$stamp_file"
        log_info "Successfully deployed core contracts to ${chain_name}"
        # Display the deployed contract addresses
        display_deployed_addresses "$chain_name"
    else
        log_error "Failed to deploy core contracts to ${chain_name}"
        exit $ERROR_DEPLOYMENT_FAILED
    fi

    # Restore default registry environment for subsequent operations
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"

    rm -rf "$temp_registry"
}

create_chain_metadata() {
    local chain_name="$1"
    local rpc_url="$2"
    local chain_id="$3"
    local output_dir="$4"
    
    cat > "${output_dir}/metadata.yaml" <<EOF
name: ${chain_name}
protocol: ethereum
chainId: ${chain_id}
domainId: ${chain_id}
rpcUrls:
  - http: ${rpc_url}
nativeToken:
  name: Ether
  symbol: ETH
  decimals: 18
EOF
    
    log_debug "Created metadata for ${chain_name}"
}


initialize_core_config() {
    local config_file="$1"

    # Reuse existing init output if present to avoid redundant work
    if [ -f "$config_file" ]; then
        log_debug "Reusing existing ${config_file}"
        return 0
    fi

    log_info "Initializing core config"

    # Ensure parent directory exists before invoking the CLI
    mkdir -p "$(dirname "$config_file")"

    # Export chain config path for CLI to recognize custom chains
    export HYP_REGISTRY="${REGISTRY_DIR}"
    export HYP_CHAINS_FILE="${REGISTRY_DIR}/chains.yaml"

    if [ "${SKIP_HYPERLANE_CORE_INIT:-false}" != "true" ]; then
        # Try to run hyperlane core init with proper flags. Provide automatic confirmation
        # so the script can run unattended.
        if yes | hyperlane core init --yes --config "$config_file" --registry "${REGISTRY_DIR}" >/tmp/core-init.log 2>&1; then
            if [ -s "$config_file" ]; then
                log_info "Successfully created core config with hyperlane core init"
                log_debug "core init output:\n$(cat /tmp/core-init.log)"
                return 0
            fi

            log_warn "hyperlane core init produced an empty config file, falling back to template"
            rm -f "$config_file"
        else
            log_warn "hyperlane core init failed; falling back to template (see /tmp/core-init.log for details)"
            tail -n 40 /tmp/core-init.log >&2 || true
        fi
    else
        log_info "Skipping hyperlane core init due to SKIP_HYPERLANE_CORE_INIT=true"
    fi

    # Fallback: Create a valid core config manually
    log_info "Creating core config with ISM type: ${ISM_TYPE:-trustedRelayer}"
    
    # Get the deployer address from the HYP_KEY
    # Using cast to derive address from private key
    local DEPLOYER_ADDRESS=""
    if [ -n "$HYP_KEY" ]; then
        DEPLOYER_ADDRESS=$(cast wallet address "$HYP_KEY" 2>/dev/null || echo "")
        log_info "Derived deployer address: $DEPLOYER_ADDRESS"
    fi
    
    # Use default address if derivation failed
    if [ -z "$DEPLOYER_ADDRESS" ]; then
        DEPLOYER_ADDRESS="0xe1A74e1FCB254CB1e5eb1245eaAe034A4D7dD538"
        log_info "Using default deployer address: $DEPLOYER_ADDRESS"
    fi
    
    # Set template directory based on environment
    local template_dir="${TEMPLATE_DIR:-/templates}"
    if [ ! -d "$template_dir" ]; then
        # Try relative path for local development
        template_dir="${SCRIPT_DIR}/../../templates"
    fi
    
    # Generate ISM configuration from template
    local ism_type="${ISM_TYPE:-trustedRelayer}"
    local ism_config=$(generate_ism_from_template "$ism_type" "$DEPLOYER_ADDRESS" "${template_dir}/ism")
    
    # Generate core configuration from template
    generate_core_config_from_template "$DEPLOYER_ADDRESS" "$ism_config" "${template_dir}/core-config.json" "$config_file"

    if [ -s "$config_file" ]; then
        log_debug "Created core config with ISM type: ${ISM_TYPE:-trustedRelayer}"
        log_debug "core config contents:\n$(cat "$config_file")"
        return 0
    else
        log_error "Failed to create core config file"
        return 1
    fi
}

deploy_core_with_retry() {
    local chain_name="$1"
    local config_file="$2"
    local registry_path="${3:-${REGISTRY_DIR}}"
    local log_file="/tmp/deploy-${chain_name}.log"
    
    log_info "Deploying Hyperlane core to ${chain_name}"
    
    # Ensure registry environment is set for deployment
    export HYP_REGISTRY="${registry_path}"
    export HYP_CHAINS_FILE="${registry_path}/chains.yaml"

    # For CLI v18+, use updated syntax
    # Define the deployment command with proper registry
    local deploy_cmd="hyperlane core deploy --chain '${chain_name}' --config '${config_file}' --registry '${registry_path}' --key '${HYP_KEY}' --yes 2>&1 | tee '${log_file}'"
    
    # Try deployment with retry on nonce errors
    local attempt=0
    while [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; do
        attempt=$((attempt + 1))
        
        if [ $attempt -gt 1 ]; then
            log_info "🔄 Deployment attempt $attempt/$MAX_RETRY_ATTEMPTS for ${chain_name}..."
        fi
        
        if eval "$deploy_cmd"; then
            if [ $attempt -gt 1 ]; then
                log_info "✅ Deployment succeeded on attempt $attempt for ${chain_name}"
            fi
            return 0
        fi

        # Check for nonce errors
        if grep -q "nonce has already been used\|nonce too low" "$log_file"; then
            if [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; then
                log_info "⚠️  Nonce error detected on ${chain_name}, this may indicate contracts are already deployed"
                log_info "🔄 Retrying deployment (attempt $attempt/$MAX_RETRY_ATTEMPTS)..."
                sleep $RETRY_DELAY
            fi
        elif grep -qi "timeout" "$log_file"; then
            if [ $attempt -lt $MAX_RETRY_ATTEMPTS ]; then
                log_info "⚠️  Timeout when deploying to ${chain_name}, retrying (attempt $attempt/$MAX_RETRY_ATTEMPTS)..."
                sleep $RETRY_DELAY
            fi
        else
            log_error "Deployment failed with non-recoverable error"
            cat "$log_file"
            return 1
        fi
    done
    
    log_error "Deployment failed after $MAX_RETRY_ATTEMPTS attempts"
    return 1
}

ensure_default_ism_recorded() {
    local chain_name="$1"
    local rpc_url="$2"
    local target_dir="$3"

    local addresses_file="${target_dir}/addresses.yaml"
    local metadata_file="${target_dir}/metadata.yaml"

    if [ ! -f "$addresses_file" ]; then
        log_warn "addresses.yaml missing for ${chain_name}; cannot record defaultIsm yet"
        return 0
    fi

    if [ -z "$rpc_url" ] && [ -f "$metadata_file" ]; then
        rpc_url=$(yq -r '.rpcUrls[0].http // ""' "$metadata_file" 2>/dev/null || echo "")
    fi

    if [ -z "$rpc_url" ]; then
        log_warn "RPC URL unavailable for ${chain_name}; skipping defaultIsm lookup"
        return 0
    fi

    if ! command -v yq >/dev/null 2>&1; then
        log_warn "yq not available; cannot inspect ${addresses_file} for ${chain_name}"
        return 0
    fi

    local mailbox_addr
    mailbox_addr=$(yq -r '.mailbox // ""' "$addresses_file" 2>/dev/null || echo "")

    if [ -z "$mailbox_addr" ]; then
        log_warn "Mailbox address missing in registry for ${chain_name}; skipping defaultIsm lookup"
        return 0
    fi

    if ! command -v cast >/dev/null 2>&1; then
        log_warn "cast binary not available; cannot query defaultIsm for ${chain_name}"
        return 0
    fi

    local ism_addr
    ism_addr=$(cast call "$mailbox_addr" "defaultIsm()(address)" --rpc-url "$rpc_url" 2>/dev/null | tr -d '\r' || echo "")

    if [ -z "$ism_addr" ]; then
        log_warn "Failed to query defaultIsm for ${chain_name} via ${mailbox_addr}"
        return 0
    fi

    ism_addr=$(echo "$ism_addr" | tr '[:upper:]' '[:lower:]')

    if [ "$ism_addr" = "0x0000000000000000000000000000000000000000" ]; then
        log_warn "defaultIsm for ${chain_name} returned the zero address; leaving registry unchanged"
        return 0
    fi

    ISM_VALUE="$ism_addr" yq -i '.defaultIsm = strenv(ISM_VALUE) | (.defaultIsm tag="!!str") | (.defaultIsm style="double") | .interchainSecurityModule = strenv(ISM_VALUE) | (.interchainSecurityModule tag="!!str") | (.interchainSecurityModule style="double")' "$addresses_file"
    log_info "Recorded defaultIsm ${ism_addr} for ${chain_name} in registry"

    local json_file="${CONFIGS_DIR}/addresses-${chain_name}.json"
    if [ -f "$json_file" ]; then
        ISM_VALUE="$ism_addr" yq -i -o=json '.defaultIsm = strenv(ISM_VALUE) | .interchainSecurityModule = strenv(ISM_VALUE) | .ism = strenv(ISM_VALUE)' "$json_file" 2>/dev/null || true
        log_debug "Updated ${json_file} with defaultIsm ${ism_addr}"
    fi

    return 0
}

copy_deployment_artifacts() {
    local chain_name="$1"
    local target_dir="$2"
    local rpc_url="$3"
    local addresses_file="$HOME/.hyperlane/chains/${chain_name}/addresses.yaml"

    if [ -f "$addresses_file" ]; then
        cp "$addresses_file" "$target_dir/"
        log_debug "Copied deployment artifacts for ${chain_name}"
    else
        log_warn "Expected addresses.yaml not found in CLI cache for ${chain_name}"
    fi

    ensure_default_ism_recorded "$chain_name" "$rpc_url" "$target_dir"
    local registry_type
    registry_type=$(yq -r '.defaultIsm | type' "$target_dir/addresses.yaml" 2>/dev/null || echo "")
    log_debug "defaultIsm YAML type for ${chain_name} registry: ${registry_type}"

    local cli_chain_dir="$HOME/.hyperlane/chains/${chain_name}"
    if [ -d "$cli_chain_dir" ]; then
        ensure_default_ism_recorded "$chain_name" "$rpc_url" "$cli_chain_dir"
        local cli_type
        cli_type=$(yq -r '.defaultIsm | type' "$cli_chain_dir/addresses.yaml" 2>/dev/null || echo "")
        log_debug "defaultIsm YAML type for ${chain_name} CLI cache: ${cli_type}"
    fi
}

display_deployed_addresses() {
    local chain_name="$1"
    local registry_file="${REGISTRY_DIR}/chains/${chain_name}/addresses.yaml"

    if [ -f "$registry_file" ]; then
        log_info "✅ Core contract deployments complete for ${chain_name}:"
        echo ""
        # Display the addresses with proper formatting
        while IFS=': ' read -r key value; do
            if [ -n "$key" ] && [ -n "$value" ]; then
                echo "    $key: $value"
            fi
        done < "$registry_file"
        echo ""
    else
        log_warn "Could not find deployed addresses for ${chain_name}"
    fi
}

# ============================================================================
# S3 BUCKET CONFIGURATION
# ============================================================================

configure_s3_bucket_policy() {
    local bucket="${S3_BUCKET:-}"

    if [ -z "$bucket" ]; then
        log_info "Skipping S3 bucket policy configuration (S3_BUCKET not set)"
        return 0
    fi

    if ! command -v aws >/dev/null 2>&1; then
        log_warn "AWS CLI not available; cannot configure S3 bucket policy for ${bucket}"
        return 0
    fi

    local region="${S3_REGION:-us-east-1}"
    local prefix="${S3_PREFIX:-}"
    local folder="${S3_FOLDER:-validator}"

    folder="${folder#/}"
    folder="${folder%/}"

    local base_prefix=""
    if [ -n "$prefix" ]; then
        base_prefix="${prefix%/}/"
    fi

    local validator_prefix="${base_prefix}${folder}/"
    local bare_validator_prefix="${folder}/"

    local prefixes=("${validator_prefix}" "${validator_prefix}*")
    local resources=("arn:aws:s3:::${bucket}/${validator_prefix}*")

    if [ "$bare_validator_prefix" != "$validator_prefix" ]; then
        prefixes+=("${bare_validator_prefix}" "${bare_validator_prefix}*")
        resources+=("arn:aws:s3:::${bucket}/${bare_validator_prefix}*")
    fi

    local prefix_json=""
    local resource_json=""

    local idx
    for idx in "${!prefixes[@]}"; do
        local value="${prefixes[$idx]}"
        if [ "$idx" -lt $((${#prefixes[@]} - 1)) ]; then
            prefix_json+="            \"${value}\",\n"
        else
            prefix_json+="            \"${value}\"\n"
        fi
    done

    for idx in "${!resources[@]}"; do
        local value="${resources[$idx]}"
        if [ "$idx" -lt $((${#resources[@]} - 1)) ]; then
            resource_json+="        \"${value}\",\n"
        else
            resource_json+="        \"${value}\"\n"
        fi
    done

    # Use a wildcard principal to avoid cross-account AccessDenied errors; access
    # is still scoped to the validator prefixes defined below.
    local principal_json="\"*\""

    cat > /tmp/s3-policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowValidatorList",
      "Effect": "Allow",
      "Principal": ${principal_json},
      "Action": ["s3:ListBucket"],
      "Resource": "arn:aws:s3:::${bucket}",
      "Condition": {
        "StringLike": {
          "s3:prefix": [
$(printf "%b" "$prefix_json")          ]
        }
      }
    },
    {
      "Sid": "AllowPrefixInspection",
      "Effect": "Allow",
      "Principal": ${principal_json},
      "Action": ["s3:ListBucket"],
      "Resource": "arn:aws:s3:::${bucket}",
      "Condition": {
        "StringLike": {
          "s3:prefix": [
            "${base_prefix}",
            "${base_prefix}*"
          ]
        }
      }
    },
    {
      "Sid": "AllowValidatorObjects",
      "Effect": "Allow",
      "Principal": ${principal_json},
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:PutObjectAcl"
      ],
      "Resource": [
$(printf "%b" "$resource_json")      ]
    }
  ]
}
EOF

    if aws --region "$region" s3api put-bucket-policy --bucket "$bucket" --policy file:///tmp/s3-policy.json >/tmp/s3-policy.log 2>&1; then
        log_info "Configured S3 bucket policy for ${bucket} (prefix ${validator_prefix})"

        # Capture resulting policy and a quick prefix listing for debugging
        if aws --region "$region" s3api get-bucket-policy --bucket "$bucket" >/tmp/s3-policy-effective.json 2>/tmp/s3-policy-effective.err; then
            log_debug "Effective S3 bucket policy: $(cat /tmp/s3-policy-effective.json)"
        else
            log_warn "Unable to read back bucket policy for ${bucket}: $(cat /tmp/s3-policy-effective.err)"
        fi

        if aws --region "$region" s3 ls "s3://${bucket}/${validator_prefix}" >/tmp/s3-prefix-list.log 2>/tmp/s3-prefix-list.err; then
            log_debug "Verified read access to s3://${bucket}/${validator_prefix}"
        else
            log_warn "Failed to list s3://${bucket}/${validator_prefix}: $(cat /tmp/s3-prefix-list.err)"
        fi
    else
        log_warn "Failed to configure S3 bucket policy for ${bucket}: $(cat /tmp/s3-policy.log)"
    fi
}

# ============================================================================
# CORE CONFIG APPLICATION & IGP FUNDING
# ============================================================================

hyperlane_supports_command() {
    local command_name="$1"
    if ! command -v hyperlane >/dev/null 2>&1; then
        return 1
    fi

    # yargs prints the list of commands when an unknown one is requested; guard against false positives
    local help_output
    help_output=$(hyperlane help 2>/dev/null || true)
    if echo "$help_output" | grep -q "hyperlane ${command_name}[^a-zA-Z]"; then
        return 0
    fi

    return 1
}

apply_core_configs() {
    log_info "Applying Hyperlane core configuration to register remote routers"

    if ! command -v hyperlane >/dev/null 2>&1; then
        log_warn "Hyperlane CLI not found; skipping core apply step"
        return 0
    fi

    local -a apply_chains=()
    IFS=',' read -r -a apply_chains <<< "${CHAIN_NAMES}"
    for chain in "${apply_chains[@]}"; do
        local core_cfg="${CONFIGS_DIR}/core-${chain}.yaml"
        local apply_stamp="${CONFIGS_DIR}/.done-core-apply-${chain}"

        if [ ! -f "$core_cfg" ]; then
            log_warn "Core config ${core_cfg} not found; skipping apply for ${chain}"
            continue
        fi

        if [ ! -s "$core_cfg" ]; then
            log_warn "Core config ${core_cfg} is empty; skipping apply for ${chain}"
            continue
        fi

        if check_stamp_file "$apply_stamp"; then
            log_info "Core apply already completed for ${chain}, skipping"
            continue
        fi

        log_info "Running core apply for ${chain} using ${core_cfg}"
        local apply_log="/tmp/core-apply-${chain}.log"

        if hyperlane core apply \
            --chain "${chain}" \
            --config "${core_cfg}" \
            --registry "${REGISTRY_DIR}" \
            --key "${HYP_KEY}" \
            --yes 2>&1 | tee "$apply_log"; then
            log_info "✅ Successfully applied core config on ${chain}"
            log_debug "core apply log (${chain}):\n$(tail -n 40 "$apply_log")"
            create_stamp_file "$apply_stamp"
        else
            log_warn "⚠️  Failed to apply core config on ${chain}; inspect ${apply_log} for details"
            tail -n 40 "$apply_log" >&2 || true
        fi
    done
}

fund_igp_deposits() {
    if [ "${RUN_IGP_FUND:-true}" != "true" ]; then
        log_info "IGP funding step disabled via RUN_IGP_FUND=${RUN_IGP_FUND:-false}"
        return 0
    fi

    if ! hyperlane_supports_command "igp"; then
        local cli_version
        cli_version=$(hyperlane --version 2>/dev/null | tail -n 1 | tr -d '\r' || echo "unknown")
        log_warn "Installed Hyperlane CLI (${cli_version}) does not expose 'hyperlane igp'; skipping automated IGP funding"
        return 0
    fi

    local amount="${IGP_FUND_AMOUNT:-0.25}"
    log_info "Funding Interchain Gas Paymasters with ${amount} ETH per route"

    local -a fund_chains=()
    IFS=',' read -r -a fund_chains <<< "${CHAIN_NAMES}"
    for origin in "${fund_chains[@]}"; do
        local igp_entry
        igp_entry=$(grep -E "^interchainGasPaymaster:" "${REGISTRY_DIR}/chains/${origin}/addresses.yaml" 2>/dev/null || true)
        if [ -z "$igp_entry" ]; then
            log_warn "No interchainGasPaymaster address registered for ${origin}; skipping"
            continue
        fi

        for destination in "${fund_chains[@]}"; do
            if [ "$origin" = "$destination" ]; then
                continue
            fi

            local fund_stamp="${CONFIGS_DIR}/.done-igp-fund-${origin}-to-${destination}"
            if check_stamp_file "$fund_stamp"; then
                continue
            fi

            local fund_log="/tmp/igp-fund-${origin}-to-${destination}.log"
            log_info "Funding IGP on ${origin} for destination ${destination}"

            if hyperlane igp fund \
                --origin "${origin}" \
                --destination "${destination}" \
                --amount "${amount}" \
                --registry "${REGISTRY_DIR}" \
                --key "${HYP_KEY}" \
                --yes 2>&1 | tee "$fund_log"; then
                log_info "✅ Funded IGP on ${origin} for ${destination}"
                create_stamp_file "$fund_stamp"
            else
                log_warn "⚠️  Failed to fund IGP on ${origin} for ${destination}; inspect ${fund_log}"
                tail -n 40 "$fund_log" >&2 || true
            fi
        done
    done
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
    # Validate required environment variables
    require_env_var "CHAIN_NAMES" "CHAIN_NAMES not set"
    require_env_var "HYP_KEY" "HYP_KEY not set (agents.deployer.key). Required for core deployment."

    # Install CLI if needed
    ensure_hyperlane_cli

    # Create necessary directories
    ensure_directories "$CONFIGS_DIR" "${REGISTRY_DIR}"

    # Initialize chain registry BEFORE any deployments
    initialize_chain_registry

    # Ensure S3 bucket policy allows validator announce/checkpoint operations
    configure_s3_bucket_policy

    # Parse chain configurations
    declare -A RPCS
    declare -A IDS
    parse_key_value_pairs "${CHAIN_RPCS:-}" RPCS
    parse_key_value_pairs "${CHAIN_IDS:-}" IDS
    
    # Deploy to each chain
    IFS=',' read -r -a CHAINS <<< "${CHAIN_NAMES}"
    for chain in "${CHAINS[@]}"; do
        # Validate chain name
        validate_chain_name "$chain"
        
        # Get RPC URL
        rpc="${RPCS[$chain]:-}"
        if [ -z "$rpc" ]; then
            log_error "No RPC URL provided for chain ${chain}"
            exit $ERROR_MISSING_ENV
        fi
        
        # Get or detect chain ID
        chain_id=$(get_chain_id "$chain" "$rpc" "${IDS[$chain]:-}")
        
        # Deploy core to this chain
        deploy_core_to_chain "$chain" "$rpc" "$chain_id"
    done

    # Ensure default ISM addresses are captured after all deployments
    for chain in "${CHAINS[@]}"; do
        rpc="${RPCS[$chain]:-}"
        ensure_default_ism_recorded "$chain" "$rpc" "${REGISTRY_DIR}/chains/${chain}"
    done

    # Deploy IGP contracts if enabled (optional but recommended for production)
    if [ "${DEPLOY_IGP:-true}" = "true" ]; then
        log_info "Deploying InterchainGasPaymaster (IGP) contracts..."

        # Get deployer address for IGP configuration
        local DEPLOYER_ADDRESS=""
        if [ -n "$HYP_KEY" ]; then
            DEPLOYER_ADDRESS=$(cast wallet address "$HYP_KEY" 2>/dev/null || echo "")
        fi

        if [ -z "$DEPLOYER_ADDRESS" ]; then
            log_warn "Could not derive deployer address, skipping IGP deployment"
        else
            for chain in "${CHAINS[@]}"; do
                local igp_stamp="${CONFIGS_DIR}/.done-igp-${chain}"

                # Skip if already deployed
                if check_stamp_file "$igp_stamp"; then
                    log_info "IGP already deployed for ${chain}, skipping"
                    continue
                fi

                log_info "Deploying IGP for ${chain}..."

                # Create minimal IGP hook configuration
                cat > "/tmp/igp-hook-${chain}.yaml" <<EOF
type: interchainGasPaymaster
beneficiary: "${DEPLOYER_ADDRESS}"
owner: "${DEPLOYER_ADDRESS}"
oracleKey: "${DEPLOYER_ADDRESS}"
gasOracleType: storageGasOracle
overhead:
  default: 50000
EOF

                # Try to deploy using hyperlane CLI
                local deploy_log="/tmp/deploy-igp-${chain}.log"
                if hyperlane deploy hook \
                    --chain "${chain}" \
                    --config "/tmp/igp-hook-${chain}.yaml" \
                    --registry "${REGISTRY_DIR}" \
                    --key "${HYP_KEY}" \
                    --yes 2>&1 | tee "$deploy_log"; then

                    # Try to extract IGP address from deployment output
                    # Look for patterns like "InterchainGasPaymaster deployed at: 0x..."
                    local igp_addr=$(grep -oP 'InterchainGasPaymaster.*?0x[a-fA-F0-9]{40}' "$deploy_log" | grep -oP '0x[a-fA-F0-9]{40}' | head -1)

                    # Alternative pattern matching if first fails
                    if [ -z "$igp_addr" ]; then
                        igp_addr=$(grep -oP 'deployed.*?0x[a-fA-F0-9]{40}' "$deploy_log" | grep -oP '0x[a-fA-F0-9]{40}' | head -1)
                    fi

                    if [ -n "$igp_addr" ]; then
                        # Update addresses.yaml with IGP address
                        local addr_file="${REGISTRY_DIR}/chains/${chain}/addresses.yaml"

                        # Check if interchainGasPaymaster already exists in file
                        if grep -q "^interchainGasPaymaster:" "$addr_file" 2>/dev/null; then
                            # Update existing entry
                            sed -i "s/^interchainGasPaymaster:.*/interchainGasPaymaster: ${igp_addr}/" "$addr_file"
                        else
                            # Add new entry
                            echo "interchainGasPaymaster: ${igp_addr}" >> "$addr_file"
                        fi

                        # Also update JSON addresses file if it exists
                        local json_file="${CONFIGS_DIR}/addresses-${chain}.json"
                        if [ -f "$json_file" ]; then
                            # Use yq to update JSON
                            yq -i '.interchainGasPaymaster = "'${igp_addr}'"' -o json "$json_file" 2>/dev/null || true
                        fi

                        log_info "✅ IGP deployed for ${chain} at: ${igp_addr}"
                        create_stamp_file "$igp_stamp"
                    else
                        log_warn "⚠️  IGP deployed but could not extract address for ${chain}"
                        # Still mark as done to avoid re-deployment attempts
                        create_stamp_file "$igp_stamp"
                    fi
                else
                    log_warn "⚠️  IGP deployment failed for ${chain}, continuing with zero address fallback"
                    # Don't create stamp file so it can be retried if needed
                fi

                # Small delay between deployments to avoid nonce issues
                sleep 2
            done
        fi
    else
        log_info "IGP deployment disabled (DEPLOY_IGP=false), using zero address as placeholder"
    fi

    if [ "${RUN_CORE_APPLY:-true}" = "true" ]; then
        apply_core_configs
    else
        log_info "Core apply step disabled via RUN_CORE_APPLY=${RUN_CORE_APPLY:-false}"
    fi

    fund_igp_deposits

    # Mark overall deployment as complete
    create_stamp_file "${CONFIGS_DIR}/.deploy-core"
    log_info "Core deployment completed for all chains"
}

# Run main function
main "$@"
